version: '3.8'

services:
  api:
    tty: true
    image: backend-base-dev
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      target: dev
    volumes:
      - ./lib:/home/node/app/lib
      - ./migrations:/home/node/app/migrations
    ports:
      - '${PORT}'
    depends_on:
      - mongo
      - postgres
      - redis
    env_file: .env
    environment:
      MONGODB_HOST: mongo
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

  mongo:
    image: mongo
    ports:
      - '${MONGODB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGODB_DBNAME}'

  postgres:
    image: postgres:alpine
    ports:
      - '${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}'
